BoudinAhmed/SystemTroubleShooter

WindowsTroubleShooter/Helpers/Converters/StatusToBrushConverter.cs
WindowsTroubleShooter/Model/HistoryEntryModel.cs
WindowsTroubleShooter/Resources/Styles.xaml
WindowsTroubleShooter/View/DashboardView.xaml
WindowsTroubleShooter/View/ProblemListView.xaml
WindowsTroubleShooter/View/ProblemListView.xaml.cs
WindowsTroubleShooter/View/StartView.xaml
WindowsTroubleShooter/ViewModel/ProblemListViewModel.cs
WindowsTroubleShooter/WindowsTroubleShooter.csproj

UI Update: completed Dashboard layout design and problem list design

UI Update: completed Dashboard layout design and problem list design

---

WindowsTroubleShooter/Resources/Styles.xaml
WindowsTroubleShooter/View/StartView.xaml
WindowsTroubleShooter/ViewModel/DashboardViewModel.cs
WindowsTroubleShooter/ViewModel/ProblemListViewModel.cs
WindowsTroubleShooter/ViewModel/ViewModelBase.cs

Refractor: cleaned code in both dashboard and problemlist viewmodel

Refractor: cleaned code in both dashboard and problemlist viewmodel

---

WindowsTroubleShooter/View/DashboardView.xaml
WindowsTroubleShooter/View/ProblemListView.xaml
WindowsTroubleShooter/View/StartView.xaml
WindowsTroubleShooter/ViewModel/ProblemListViewModel.cs
WindowsTroubleShooter/ViewModel/StartViewModel.cs

Feature: able to navigate to different content within the view using sidebar buttons

Feature: able to navigate to different content

---

WindowsTroubleShooter/Resources/Styles.xaml
WindowsTroubleShooter/View/DashboardView.xaml
WindowsTroubleShooter/ViewModel/StartViewModel.cs

Fractor: move dashboard style elements to deticated resource style file

Fractor: move dashboard style elements to deticated resource style file

---

WindowsTroubleShooter/View/SettingsView.xaml
WindowsTroubleShooter/View/SettingsView.xaml.cs
WindowsTroubleShooter/ViewModel/IIssue.cs
WindowsTroubleShooter/ViewModel/NetworkDriveViewModel.cs
WindowsTroubleShooter/ViewModel/SettingsViewModel.cs
WindowsTroubleShooter/WindowsTroubleShooter.csproj

View contains configuration that user would be able to save in the software like the L and path of a network drive

Created a view for the settings section

---

WindowsTroubleShooter/View/AboutView.xaml
WindowsTroubleShooter/View/AboutView.xaml.cs
WindowsTroubleShooter/ViewModel/AboutViewModel.cs
WindowsTroubleShooter/ViewModel/IIssue.cs

View for the about section with content

Feature: designed the view for the about section

---

WindowsTroubleShooter/ViewModel/SettingsViewModel.cs
WindowsTroubleShooter/WindowsTroubleShooter.csproj

Feature: settings cache for network drive

Feature: settings cache for network drive

---

WindowsTroubleShooter/View/AboutView.xaml
WindowsTroubleShooter/View/ProblemListView.xaml
WindowsTroubleShooter/View/SettingsView.xaml
WindowsTroubleShooter/View/StartView.xaml
WindowsTroubleShooter/ViewModel/SettingsViewModel.cs
WindowsTroubleShooter/ViewModel/StartViewModel.cs

Fixed bugged scollbar by encapsulating the code in a stackbar and generating the scrollbar outside the stackbar

Fixed bugged scollbar

---

WindowsTroubleShooter/View/ProblemListView.xaml
WindowsTroubleShooter/View/SettingsView.xaml
WindowsTroubleShooter/ViewModel/SettingsViewModel.cs

Cache for network drive and update time frame stores

Cache for network drive and update time frame stores

---

WindowsTroubleShooter/View/SettingsView.xaml

Replace ListBox with ItemsControl for network drives to fix scroll blocking

Replace ListBox with ItemsControl for network drives to fix scroll blocking

---

WindowsTroubleShooter/View/AboutView.xaml
WindowsTroubleShooter/View/StartView.xaml
WindowsTroubleShooter/ViewModel/DashboardViewModel.cs
WindowsTroubleShooter/ViewModel/StartViewModel.cs

able to now navigate to about view using the sidebar icon

Feature: able to now navigate to about view using the sidebar icon

---

WindowsTroubleShooter.Test/StartViewModelTests.cs
WindowsTroubleShooter.Test/UnitTest1.cs
WindowsTroubleShooter.Test/Usings.cs
WindowsTroubleShooter.Test/WindowsTroubleShooter.Test.csproj
WindowsTroubleShooter.sln
WindowsTroubleShooter/ViewModel/StartViewModel.cs

Feature: adding test since UI development is finally completed

Feature: adding test since UI development is finally completed

---

WindowsTroubleShooter.Tests/StartViewModelTests.cs
WindowsTroubleShooter.Tests/UnitTest1.cs
WindowsTroubleShooter.Tests/WindowsTroubleShooter.Tests.csproj
WindowsTroubleShooter/View/AboutView.xaml
WindowsTroubleShooter/View/DashboardView.xaml
WindowsTroubleShooter/View/ProblemListView.xaml
WindowsTroubleShooter/View/SettingsView.xaml
WindowsTroubleShooter/ViewModel/DashboardViewModel.cs

Bug: see all button not switching to problem list

Bug: see all button not switching to problem list. 

---

WindowsTroubleShooter.Test/Model.Test/InternetTroubleshooterTest.cs
WindowsTroubleShooter/Model/Troubleshooter/BaseTroubleshooter.cs
WindowsTroubleShooter/Model/Troubleshooter/InternetTroubleshooter.cs
WindowsTroubleShooter/Model/Troubleshooter/NetworkDriveTroubleshooter.cs
WindowsTroubleShooter/Scripts/NetworkDrive/MapNetworkDrive.ps1
WindowsTroubleShooter/ViewModel/HomeViewModel.cs
WindowsTroubleShooter/ViewModel/SettingsViewModel.cs
WindowsTroubleShooter/WindowsTroubleShooter.csproj

Bug: Correctly handle backslashes in network drive paths

Bug: Correctly handle backslashes in network drive paths

---

SystemTroubleShooter/App.xaml.cs
SystemTroubleShooter/SystemTroubleShooter.csproj
SystemTroubleShooter/View/ResultWindowView.xaml
SystemTroubleShooter/View/ResultWindowView.xaml.cs
SystemTroubleShooter/ViewModel/ResultWindowViewModel.cs

Feature: result window design once the troubleshooting is complete

Feature: result window design once the troubleshooting is complete

---

SystemTroubleShooter/Scripts/Internet/IsNetworkAdaptersAvailable.ps1
SystemTroubleShooter/Scripts/Internet/RefreshNetworkAdapter.ps1

Fix: Corrected script logic for waiting for adapter status 'Up'

Fix: Corrected script logic for waiting for adapter status 'Up'

---

SystemTroubleShooter/Model/Troubleshooter/SoundTroubleshooter.cs
SystemTroubleShooter/SystemTroubleShooter.csproj
SystemTroubleShooter/View/AboutView.xaml
SystemTroubleShooter/View/StartView.xaml
SystemTroubleShooter/ViewModel/HomeViewModel.cs

Feature: sound troubleshooter model. Currently getting default audio volume and microphone status

Feature: sound troubleshooter model. Currently getting default device volume and mic status

---

SystemTroubleShooter/Resources/Styles.xaml

Bug: viewport binding error. fix:  adjust the size of the thumb based on the scrollable content's size

Bug: viewport binding error. fix:  adjust the size of the thumb

---

SystemTroubleShooter/Model/Troubleshooter/InternetTroubleshooter.cs
SystemTroubleShooter/Model/Troubleshooter/SoundTroubleshooter.cs
SystemTroubleShooter/Scripts/Sound/Check-Restart-AudioServices.ps1
SystemTroubleShooter/Scripts/Sound/GetAllAudioDevices.ps1
SystemTroubleShooter/SystemTroubleShooter.csproj
SystemTroubleShooter/ViewModel/StartViewModel.cs

Feature: added audio script, code clean up

Feature: added audio script, code clean up

---

SystemTroubleShooter/Model/Troubleshooter/SoundTroubleshooter.cs
SystemTroubleShooter/Scripts/Sound/GetAllAudioDevices.ps1
SystemTroubleShooter/SystemTroubleShooter.csproj

Refractor: sound script and model to get all devices based on name

Refractor: sound script and model to get all devices based on name

---

SystemTroubleShooter/Helpers/AudioDeviceDisplayService.cs
SystemTroubleShooter/Interfaces/IAudioDeviceDisplayService.cs
SystemTroubleShooter/View/SoundDevicesView.xaml
SystemTroubleShooter/View/SoundDevicesView.xaml.cs
SystemTroubleShooter/ViewModel/IssueItemViewModel.cs
SystemTroubleShooter/ViewModel/SoundDevicesViewModel.cs

Feature:  dialog box for audio device selection

Feature: dialog box for audio device selection

---

SystemTroubleShooter/View/SoundDevicesView.xaml
SystemTroubleShooter/ViewModel/SoundDevicesViewModel.cs

Bug: buttons snap to the top instead of transitioning. modified the visibility from collapsed to hidden

 Bug: buttons snap to the top instead of transitioning.

---

SystemTroubleShooter/Helpers/AudioDeviceDisplayService.cs
SystemTroubleShooter/Model/Troubleshooter/SoundTroubleshooter.cs
SystemTroubleShooter/Scripts/Sound/GetAllAudioDevices.ps1
SystemTroubleShooter/ViewModel/IssueItemViewModel.cs
SystemTroubleShooter/ViewModel/SoundDevicesViewModel.cs

Refractor: modified script to return both input and output, implemented logic to display all output/input in sounddevices view

Refractor: modified script to return both input and output

---

SystemTroubleShooter/Helpers/AudioDeviceDisplayService.cs
SystemTroubleShooter/Interfaces/IAudioDeviceDisplayService.cs
SystemTroubleShooter/Model/Troubleshooter/SoundTroubleshooter.cs
SystemTroubleShooter/View/SoundDevicesView.xaml
SystemTroubleShooter/View/SoundDevicesView.xaml.cs
SystemTroubleShooter/ViewModel/HomeViewModel.cs
SystemTroubleShooter/ViewModel/IssueItemViewModel.cs
SystemTroubleShooter/ViewModel/SoundDevicesViewModel.cs
SystemTroubleShooter/ViewModel/StartViewModel.cs

Feature: Process of user select audio device complete

Feature: Process of user select audio device complete

---

SystemTroubleShooter/App.xaml.cs
SystemTroubleShooter/Helpers/Services/AudioDeviceDisplayService.cs
SystemTroubleShooter/Helpers/Services/DialogService.cs
SystemTroubleShooter/Helpers/Services/NavigationService.cs
SystemTroubleShooter/Interfaces/IDialogService.cs
SystemTroubleShooter/SystemTroubleShooter.csproj
SystemTroubleShooter/View/CompletionMessageView.xaml
SystemTroubleShooter/View/CompletionMessageView.xaml.cs
SystemTroubleShooter/ViewModel/CompletionMessageViewModel.cs
SystemTroubleShooter/ViewModel/IssueItemViewModel.cs
SystemTroubleShooter/ViewModel/SoundDevicesViewModel.cs

Feature: Completion message box after troubleshooting

Feature: Completion message box after troubleshooting

---

SystemTroubleShooter/App.xaml.cs

Fix: build error

---

.github/workflows/codeql.yml

Initial codeql analysis yaml commit

codeql-analysis.yml

---

SystemTroubleShooter.Test/Model.Test/InternetTroubleshooterTests.cs

Code Quality: Updated tests to match changes to internet troubleshooter and powershell handling

Code Quality: Updated tests to match changes to internet troubleshooter

---

SystemTroubleShooter/Model/Troubleshooter/SoundTroubleshooter.cs
SystemTroubleShooter/View/SettingsView.xaml
SystemTroubleShooter/ViewModel/IssueItemViewModel.cs
SystemTroubleShooter/ViewModel/SettingsViewModel.cs

Feature: Displaying output device list on the drop down in settings

Feature: Displaying output device list on the drop down in settings

---

SystemTroubleShooter/ViewModel/SettingsViewModel.cs

Bug: Settings resets back to default after a few refreshs, fixed the loadsettings method

Bug: Settings resets back to default after a few refreshs, fixed the loadsettings method

---

SystemTroubleShooter/View/CompletionMessageView.xaml
SystemTroubleShooter/View/CompletionMessageView.xaml.cs
SystemTroubleShooter/View/SoundDevicesView.xaml
SystemTroubleShooter/View/SoundDevicesView.xaml.cs

Feature: Ability to drag completion and sound devices window

Feature: Ability to drag completion and sound devices window
